config/routes.rb
Rails.application.routes.draw do
  resources :posts
  resources :comments, only: [:create, :destroy]
  devise_for :users

  authenticated :user do
    root to: 'home#index', as: 'home'
  end

  unauthenticated :user do
    root 'home#front'
  end

  get "profile" => "people#show", :as => "profile"

  get "people" => "people#index", :as => "people"
  post "people" => "people#friends"
  get "userFriends" => "people#userFriends", :as => "userFriends"

  get "share" => "posts#share", :as => "share"

  get "manage" => "controls#index", :as => "manage"
  post "manage" => "controls#manage"

  match :like, to: 'likes#create', as: :like, via: :post
  match :unlike, to: 'likes#destroy', as: :unlike, via: :post

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :find_likeable
  before_action :authenticate_user!
  respond_to :js

  def create
    @likeable.liked_by current_user
    redirect_to :back
  end

  def destroy
    @likeable.disliked_by current_user
    redirect_to :back
  end

  private
  def find_likeable
    @likeable_type = params[:likeable_type].classify
    @likeable = @likeable_type.constantize.find(params[:likeable_id])
  end
end

app/views/likes/_form.html.erb
<% if current_user.liked? likeable %>
  <%= form_tag unlike_path(likeable_type: likeable.class.to_s, likeable_id: likeable.id), method: :post, remote: true, class: 'form-like' do %>
    <% button_tag class: 'btn btn-danger liked' do %>
       Unlike
    <% end %>
  <% end %>
<% else %>
  <%= form_tag like_path(likeable_type: likeable.class.to_s, likeable_id: likeable.id), remote: true, class: 'form-like' do %>
    <% button_tag class: 'btn btn-primary' do %>
       Like
    <% end %>
  <% end %>
<% end %>